// Generated by https://quicktype.io

export interface Data {
  content:          Teams[];
  pageable:         Pageable;
  totalPages:       number;
  totalElements:    number;
  last:             boolean;
  first:            boolean;
  numberOfElements: number;
  sort:             Sort;
  size:             number;
  number:           number;
  empty:            boolean;
}

export interface Teams {
  id:           number;
  nombre:       string;
  estadio:      string;
  sitioWeb:     null;
  nacionalidad: string;
  fundacion:    string;
  entrenador:   string;
  capacidad:    number;
  valor:        null;
}

export interface Pageable {
  sort:       Sort;
  pageSize:   number;
  pageNumber: number;
  offset:     number;
  paged:      boolean;
  unpaged:    boolean;
}

export interface Sort {
  sorted:   boolean;
  unsorted: boolean;
  empty:    boolean;
}
